// Basic Stats
max_hp = 0;
hp = max_hp;
base_spd = 0.0;
spd = base_spd;
contact_damage      = 0; // damage dealt to the tower per hit
dmg = contact_damage;
attack_rate_frames  = 30;   // cooldown between hits (~0.5s at 60fps)
attack_cooldown     = 0;    // counts down in Step
stop_margin_px      = 6;    // how far from the tower to stop before attacking
hurt_timer = 0;
blind_timer = 0;
hit_radius = 10;
xp_value = 0;
points = 1;
hit_flash = 0;
enemy_radius = 0;
image_angle = 0;
blind_t = 0; 
target_boat              = noone; // the specific boat this enemy will pursue
retarget_cooldown_frames = 15;    // how often the enemy is allowed to switch boats
retarget_cd              = 0;     // counts down each Step